services:
  flyway-maplekiosk:
    image: flyway/flyway:11.9.2-alpine
    container_name: flyway-maplekiosk
    volumes:
      - ./flyway/maplekiosk:/flyway/sql
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["/bin/sh", "/wait-for-it.sh", "mariadb:3306", "--", "flyway", "migrate"]
    command: -url=jdbc:mariadb://mariadb:3306/${DB_MAPLE_KIOSK_NAME} -user=${DB_USER} -password=${DB_PASSWORD} migrate
    networks:
      - maplekiosk-network

  flyway-auth:
    image: flyway/flyway:11.8.2
    container_name: flyway-auth
    volumes:
      - ./flyway/auth:/flyway/sql
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["/bin/sh", "/wait-for-it.sh", "mariadb:3306", "--", "flyway", "migrate"]
    command: -url=jdbc:mariadb://mariadb:3306/${DB_AUTH_NAME} -user=${DB_USER} -password=${DB_PASSWORD} migrate
    networks:
      - maplekiosk-network

networks:
  maplekiosk-network:
    external: true