#!/bin/bash
source .env
cat << SQL > ./mariadb/init.sql
CREATE DATABASE IF NOT EXISTS \`${DB_MAPLE_KIOSK_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${DB_AUTH_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT SELECT ON \`${DB_MAPLE_KIOSK_NAME}\`.* TO '${DB_USER}'@'%';
GRANT SELECT ON \`${DB_AUTH_NAME}\`.* TO '${DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${MAPLE_KIOSK_USER_NAME}'@'%' IDENTIFIED BY '${MAPLE_KIOSK_USER_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${DB_MAPLE_KIOSK_NAME}\`.* TO '${MAPLE_KIOSK_USER_NAME}'@'%';

CREATE USER IF NOT EXISTS '${AUTH_USER_NAME}'@'%' IDENTIFIED BY '${AUTH_USER_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${DB_AUTH_NAME}\`.* TO '${AUTH_USER_NAME}'@'%';

FLUSH PRIVILEGES;
SQL
chmod 644 ./mariadb/init.sql
